export default {
    CONNECTED: `SERVER IS CONNECTED ON PORT : ${process.env.PORT}`,
    AUTHENTICATE_MESSAGE: "DELIVERY CHALLAN DATABASE AUTHENTICATED",
    DATABASE_CONNECTION_MESSAGE: "DATABASE IS CONNECTED",
    // OTP_SENT: "OTP SENT!",
    // OTP_VALIDATED: "OTP VERIFICATION SUCCESSFUL",
    // Invalid_OTP: "OTP INVALID",
    // OTP_EXPIRED_OR_USED: "PROVIDED OTP EITHER EXPIRED OR USED",
    UserNotExist: "USER NOT FOUND",
    UserExist: "USER EXIST",
    UserLoggedIn: "USER LOGGED IN SUCCESSFULLY",
    INCORRECT_PASSWORD: "INCORRECT PASSWORD",
    USER_NOT_VERFIED: "USER IS NOT VERIFIED",
    USER_FOUND: "USER DETAIL FETCHED",
    TOKEN_NOT_FOUND: "TOKEN NOT FOUND",
    INVALID_TOKEN: "INVALID TOKEN",
    USER_PROFILE_UPDATED: "USER PROFILE UPDATED"
};